config/routes.rb
Rails.application.routes.draw do

  resources :orders

  resources :line_items

  resources :carts

  devise_for :users, :controllers => {:sessions => "users/sessions", :registrations => "users/registrations"}
  resources :cloths
  get 'cloth_by_category' => 'cloths#cloth_by_category'
  

  resources :users

  root 'cloths#home'
  get 'home_mobile' => 'cloths#home_mobile'
  

end

app/models/order.rb
class Order < ActiveRecord::Base

STATUS = ["SEEN", "ARRIVED"]


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:new, :create]
  respond_to :html

  def index
    @orders = Order.all
    respond_with(@orders)
  end

  def show
    respond_with(@order)
  end

  def new
    @order = Order.new
    respond_with(@order)
  end

  def edit
  end

  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        session[:cart_id] = nil
        format.html { redirect_to @order, notice: 'Cloth was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @order.update(order_params)
    respond_with(@order)
  end

  def destroy
    @order.destroy
    respond_with(@order)
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:status, :cart_id, :customer_name, :nrc, :contact_phone, :shipping_address)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/edit.html.erb
<div class="container">
<h1>Editing order</h1>


 <%= form_for @order, :html => {:class =>"form-horizontal"} do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :status %><br>
    <%= f.select(:status, Order::STATUS) %>
  </div>

  <div class="form-group">
    <%= f.label :customer_name %><br>
    <%= f.text_field :customer_name , :class=>"form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :nrc %><br>
    <%= f.text_field :nrc, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :contact_phone %><br>
    <%= f.text_field :contact_phone, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :shipping_address %><br>
    <%= f.text_field :shipping_address, :class=>"form-control" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/orders/index.html.erb
<div class="container">
<h3>Orders DB <%= link_to 'New Cloth', new_cloth_path, :class=>"btn btn-default" %>
<%= link_to 'New Orders', orders_path, :class=>"btn btn-default" %>
</h3>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Status</th>
      <th>CustomerName</th>
      <th>Nrc</th>
      <th>Contact phone</th>
      <th>Shipping address</th>
      <th>Order Item</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.status %></td>
        <td><%= order.customer_name %></td>
        <td><%= order.nrc %></td>
        <td><%= order.contact_phone %></td>
        <td><%= order.shipping_address %></td>
        <td><%= link_to "OrderItems",line_items_path(:cart_id => order.cart_id), :method => :get %>
        </td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


</div>

app/views/orders/new.html.erb
<div class="container">
<h3>Thanks you for shopping at MiMiberry.co :D</h3>


<div class="container">

  <div class="panel panel-default" id="order_form">

      <div class="panel-heading" >Please fill up the form to complete your order.</div>
      <div class="panel-body" >
              <div class="col-md-4"></div>
              <div class="col-md-4">
                
                  <%= form_for @order, :html => {:class =>"form-horizontal", :remote => true} do |f| %>

                        <div class="form-group">
                          <%= f.text_field :cart_id , :class=>"form-control", :placeholder => "cart" , :value => session[:cart_id], :style => "display:none;" %>
                        </div>


                        <div class="form-group">
                          <label>Your Name</label><br>
                          <%= f.text_field :customer_name , :class=>"form-control", :placeholder => "FullName" %>
                        </div>
                        <div class="form-group">
                          <label>NRC</label><br>
                          <%= f.text_field :nrc, :class=>"form-control" %>
                        </div>
                        <div class="form-group">
                          <label>Phone <span style="color:red;">(order will confirm via phone within 24 hours)</span></label><br>
                          <%= f.text_field :contact_phone, :class=>"form-control" %>
                        </div>
                        <div class="form-group">
                           <label>Shipping Address</label><br>
                          <%= f.text_area :shipping_address, :class=>"form-control", :rows => 5 %>
                        </div>
                        <div class="actions">
                          <%= f.submit "Submit", :class=>"btn btn-success", :id => "hidethisorder" %>
                        </div>
                <% end %>

              </div>
              <div class="col-md-4">

              </div>
      </div>
  </div>


<div class="panel panel-default" id="confirm_message" style="display:none;">
  <div class="panel-body">
     Horayyyyyyys! We have successfully received your order.We will contact you within 24 hours.

     <a href="<%= request.env['HTTP_REFERER'] %>" style="color:#1DBAA5;">Back to home page</a>
  </div>
</div>

</div>




</div>

<script>



 $("#hidethisorder").click(function(){
     $("#order_form").hide();
     $("#confirm_message").show(10000);
  
        });
</script>

app/views/orders/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer name:</strong>
  <%= @order.customer_name %>
</p>

<p>
  <strong>Nrc:</strong>
  <%= @order.nrc %>
</p>

<p>
  <strong>Contact phone:</strong>
  <%= @order.contact_phone %>
</p>

<p>
  <strong>Shipping address:</strong>
  <%= @order.shipping_address %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>
</div>