config/routes.rb
Rails.application.routes.draw do

  resources :orders

  resources :line_items

  resources :carts

  devise_for :users, :controllers => {:sessions => "users/sessions", :registrations => "users/registrations"}
  resources :cloths
  get 'cloth_by_category' => 'cloths#cloth_by_category'
  

  resources :users

  root 'cloths#home'
  get 'home_mobile' => 'cloths#home_mobile'
  

end

app/models/cart.rb
class Cart < ActiveRecord::Base

	has_many :line_items, :dependent => :destroy

	def add_item(cloth_id)
		current_item = line_items.where(:cloth_id => cloth_id).first
		if current_item
			current_item.quantity += 1
		else
			current_item = LineItem.new(:cloth_id=> cloth_id)
			line_items << current_item
		end
		current_item
	end


	def total_price
		line_items.to_a.sum { |cloth| cloth.total_price }
	end

    def total_quantity
		line_items.to_a.sum { |cloth| cloth.quantity }
	end

	



end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to root_path, :notice => 'Invalid cart'
    else
      respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @cart }
      end
    end
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to root_path, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to root_path, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
 

  def destroy

    @cart = Cart.find(params[:id])
    @cart.destroy
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to(request.env['HTTP_REFERER'], :notice => 'Your cart is currently empty') }
      format.xml { head :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
 <div class="modal-content">
           <div class="modal-header">
             <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
             <h4 class="modal-title">Shopping Cart</h4>
           </div>
           <div class="modal-body">
            	<table class="table table-striped">
		              <thead>
		                <tr>
		                  <th>Name</th>
		                  <th>Quantity</th>
		                  <th>Price</th>
		                  <th></th>
		                </tr>
		              </thead>
		              <tbody>
		              	<%= render(cart.line_items) %>
		                <tr>
		                  <th></th>
		                  <th>Total</th>
		                  <th><%= (cart.total_price) %> Ks</th>
		                  <th>&nbsp;</th>
		                </tr>
		              </tbody>
            	</table>
           </div>
           <div class="modal-footer">

     		 <%= link_to 'Empty cart', cart, :method => :delete, :confirm => 'Are you sure?', :class => "btn btn-danger", :style => "float:left;width:27%;padding-left:0px;padding-right:0px;"%>

             <button type="button" class="btn btn-default" data-dismiss="modal" style="width:30%;float:left;padding-left:0px;padding-right:0px;">Continue</button>

        	 <%= link_to "Checkout", new_order_path, :class => "btn btn-info", :style => "float:right;width:30%;padding-left:0px;padding-right:0px;"   %>

           </div>
         </div><!-- /.modal-content -->

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<div class="cart_title" >Your Cart</div>
<table>
	<% for item in @cart.line_items %>
	<%= render(@cart.line_items) %>


<tr>
   <td><%= cloth.quantity %>&times;</td>
   <td><%= cloth.cloth.name %></td>
   <td class="item_price" ><%= number_to_currency(cloth.cloth.price) %></td>
</tr>

<% end %>

<tr class="total_line" >
  <td colspan="2" >Total</td>
  <td class="total_cell" ><%= number_to_currency(@cart.total_price) %></td>
</tr>

</table>
<%= button_to 'Empty cart', @cart, :method => :delete,
:confirm => 'Are you sure?' %>