config/routes.rb
Rails.application.routes.draw do

  resources :orders

  resources :line_items

  resources :carts

  devise_for :users, :controllers => {:sessions => "users/sessions", :registrations => "users/registrations"}
  resources :cloths
  get 'cloth_by_category' => 'cloths#cloth_by_category'
  

  resources :users

  root 'cloths#home'
  get 'home_mobile' => 'cloths#home_mobile'
  

end

app/models/cloth.rb
class Cloth < ActiveRecord::Base

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/


  CATEGORY = ["Games","Memes", "Heros", "Techs", "Animes" ]


	has_many :line_items
	before_destroy :ensure_not_referenced_by_any_line_item
	# ensure that there are no line items referencing this product
	def ensure_not_referenced_by_any_line_item
		if line_items.count.zero?
			return true
		else
			errors[:base] << "Line Items present"
			return false
		end
	end

	before_save do
  		self.item_code = self.item_name
	end

end

app/controllers/cloths_controller.rb
class ClothsController < ApplicationController
  before_action :set_cloth, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:home, :cloth_by_category]
 
  # GET /cloths
  # GET /cloths.json
  def home
      @cloths = Cloth.where(:category => "Heros" )
      @cart = current_cart
      @number_of_cloths = Cloth.count('id', :distinct => true)

  end

  def home_mobile
      @cloths = Cloth.all
      @cart = current_cart
      @number_of_cloths = Cloth.count('id', :distinct => true)

  end

  def cloth_by_category
      if params[:category]
        @cloths = Cloth.where("category = ? ", params[:category ])
      end
  end

  def index
    @cloths = Cloth.all
  end

  # GET /cloths/1
  # GET /cloths/1.json
  def show
  end

  # GET /cloths/new
  def new
    @cloth = Cloth.new
  end

  # GET /cloths/1/edit
  def edit
  end


  # POST /cloths
  # POST /cloths.json
  def create
    @cloth = Cloth.new(cloth_params)

    respond_to do |format|
      if @cloth.save
        format.html { redirect_to @cloth, notice: 'Cloth was successfully created.' }
        format.json { render :show, status: :created, location: @cloth }
      else
        format.html { render :new }
        format.json { render json: @cloth.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cloths/1
  # PATCH/PUT /cloths/1.json
  def update
    respond_to do |format|
      if @cloth.update(cloth_params)
        format.html { redirect_to @cloth, notice: 'Cloth was successfully updated.' }
        format.json { render :show, status: :ok, location: @cloth }
      else
        format.html { render :edit }
        format.json { render json: @cloth.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cloths/1
  # DELETE /cloths/1.json
  def destroy
    @cloth.avatar = nil
    @cloth.save
    @cloth.destroy
    respond_to do |format|
      format.html { redirect_to cloths_url, notice: 'Cloth was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cloth
      @cloth = Cloth.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cloth_params
      params.require(:cloth).permit(:avatar, :price, :item_code, :item_name, :category,:available_size,:available_color,:brand)
 

    end



  def layout_per_action
   if action_name == "home_mobile"
    false
   else
    "application"
   end
  end
  
end

app/helpers/cloths_helper.rb
module ClothsHelper
end

app/views/cloths/_form.html.erb
<%= form_for @cloth, :html => {:class =>"form", :multipart => true } do |f| %>
  <% if @cloth.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cloth.errors.count, "error") %> prohibited this cloth from being saved:</h2>

      <ul>
      <% @cloth.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :item_name %><br>
    <%= f.text_field :item_name, :class=>"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, :class=>"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar, :class=>"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :category %><br>
    <%= f.select(:category, Cloth::CATEGORY) %>
  </div>

  <div class="form-group">
    <%= f.label :available_size %><br>
    <%= f.text_field :available_size, :class=>"form-control" %>
  </div>
 

  <div class="form-group">
    <%= f.label :available_color %><br>
    <%= f.text_field :available_color, :class=>"form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :brand %><br>
    <%= f.text_field :brand, :class=>"form-control" %>
  </div>




 
  <div class="actions">
    <%= f.submit :class=>"btn btn-default" %>
  </div>
<% end %>

app/views/cloths/cloth_by_category.html.erb
	<!---->
	<!-- start content -->
	<div class="container">
		
	<div class="women-product">
		<div class=" w_content">
			<div class="women">
				<a href="#"><h4>Sales Item - <span><%= @number_of_cloths %> items</span> </h4></a>
				<ul class="w_nav">
					<li>Sort : </li>
			     	<li><a class="active" href="#">popular</a></li> |
			     	<li><a href="#">new </a></li> |
			     	<li><a href="#">discount</a></li> |
			     	<li><a href="#">price: Low High </a></li> 
			     <div class="clearfix"> </div>	
			     </ul>
			     <div class="clearfix"> </div>	
			</div>
		</div>
		<!-- grids_of_4 -->
		<div class="grid-product">

		<% @cloths.each do |cloth| %>
			<div class=" product-grid" id="mygrid"><br/>
			<div id="mycode">code - <%= cloth.item_code %></div>
			<div class="content_box"><a href="#">
			   	<div class="left-grid-view grid-view-left">
			   	   	  <%= image_tag cloth.avatar.url(:medium), :class =>"img-responsive watch-right", :style =>"width:320px;" %>
				   	   	<div class="mask">
	                        <div class="info">Quick View</div>
			            </div>
				   	  </a>
				   </div>
				    <h4><a href="#"><%= cloth.item_name %> </a></h4>
				     <p>Available size (<%= cloth.available_size %>)<br/>
				        Available color (<%= cloth.available_color %>)</p>
				      
				      <div>
				         <h4 style="float:left;">Price: <%= cloth.price %> Kyats<hr/>
				        <p>1 TEE 10000 Kyats<br/>
				           2 TEE 15000 Kyats<br/>
				           3 TEE 20000 Kyats</p>
				        <%= button_to 'Add to Cart' , line_items_path(:cloth_id => cloth),:class =>"btn btn-success btn-sm" %>
				        </h4>
				      </div>
			 </div>
             </div>

        <% end %>
			
			<div class="clearfix"> </div>
		</div>
	</div>
	<div class="sub-cate">
				<div class=" top-nav rsidebar span_1_of_left">
					<h3 class="cate">CATEGORIES</h3>
		  <ul class="menu">
		<li class="item1">
			<%= link_to "Games",cloth_by_category_path(:category => "Games"), :method => :get %>
		</li>
		<li class="item2">
			<%= link_to "Memes",cloth_by_category_path(:category => "Memes"), :method => :get %>
		</li>
		<li class="item3">
			<%= link_to "Heros",cloth_by_category_path(:category => "Heros"), :method => :get %>
		</li>	
		<li class="item3">
			<%= link_to "Techs",cloth_by_category_path(:category => "Techs"), :method => :get %>
		</li>
		<li class="item3">
			<%= link_to "Animes",cloth_by_category_path(:category => "Animes"), :method => :get %>
		</li>
		
				
		
	</ul>
					</div>
				<!--initiate accordion-->
		<script type="text/javascript">
			$(function() {
			    var menu_ul = $('.menu > li > ul'),
			           menu_a  = $('.menu > li > a');
			    menu_ul.hide();
			    menu_a.click(function(e) {
			        e.preventDefault();
			        if(!$(this).hasClass('active')) {
			            menu_a.removeClass('active');
			            menu_ul.filter(':visible').slideUp('normal');
			            $(this).addClass('active').next().stop(true,true).slideDown('normal');
			        } else {
			            $(this).removeClass('active');
			            $(this).next().stop(true,true).slideUp('normal');
			        }
			    });
			
			});
		</script>
					
			</div>
					<div class="fb-like-box" data-href="https://www.facebook.com/mimiberryco" data-width="300px" data-height="271px" data-colorscheme="light" data-show-faces="true" data-header="true" data-stream="false" data-show-border="true"></div>
	<div class="clearfix"> </div>
</div>


<!--shopping cart model  -->
 <div class="modal fade" id="shoppingcart" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
       <div class="modal-dialog">
            <%= render @cart %>
       </div><!-- /.modal-dialog -->
 </div><!-- /.modal -->

app/views/cloths/edit.html.erb
<div class="container">
<h1>Editing cloth</h1>

<%= render 'form' %>

<%= link_to 'Show', @cloth %> |
<%= link_to 'Back', cloths_path %>
</div>

app/views/cloths/home.html.erb
	<!---->
	<!-- start content -->
	<div class="container">
		
	<div class="women-product">
		<div class=" w_content">
			<div class="women">
				<a href="#"><h4>Sales Item - <span><%= @number_of_cloths %> items</span> </h4></a>
				<ul class="w_nav">
					<li>Sort : </li>
			     	<li><a class="active" href="#">popular</a></li> |
			     	<li><a href="#">new </a></li> |
			     	<li><a href="#">discount</a></li> |
			     	<li><a href="#">price: Low High </a></li> 
			     <div class="clearfix"> </div>	
			     </ul>
			     <div class="clearfix"> </div>	
			</div>
		</div>
		<!-- grids_of_4 -->
		<div class="grid-product">

		<% @cloths.each do |cloth| %>
			<div class=" product-grid" id="mygrid"><br/>
			<div id="mycode">code - <%= cloth.item_code %></div>
			<div class="content_box"><a href="#">
			   	<div class="left-grid-view grid-view-left">
			   	   	  <%= image_tag cloth.avatar.url(:medium), :class =>"img-responsive watch-right", :style =>"width:320px;" %>
				   	   	<div class="mask">
	                        <div class="info">Quick View</div>
			            </div>
				   	  </a>
				   </div>
				    <h4><a href="#"><%= cloth.item_name %> </a></h4>
				     <p>Available size (<%= cloth.available_size %>)<br/>
				        Available color (<%= cloth.available_color %>)</p>

				      <div>
				        <h4 style="float:left;">Price: <%= cloth.price %> Kyats<hr/>
				        <p>1 TEE 10000 Kyats<br/>
				           2 TEE 15000 Kyats<br/>
				           3 TEE 20000 Kyats</p>
				        <%= button_to 'Add to Cart' , line_items_path(:cloth_id => cloth),:class =>"btn btn-success btn-sm" %>
				        </h4><br/>
				       
				      </div>
			 </div>
             </div>

        <% end %>
			
			<div class="clearfix"> </div>
		</div>
	</div>
	<div class="sub-cate">
				<div class=" top-nav rsidebar span_1_of_left">
					<h3 class="cate">CATEGORIES</h3>
				  <ul class="menu">
		<li class="item1">
			<%= link_to "Games",cloth_by_category_path(:category => "Games"), :method => :get %>
		</li>
		<li class="item2">
			<%= link_to "Memes",cloth_by_category_path(:category => "Memes"), :method => :get %>
		</li>
		<li class="item3">
			<%= link_to "Heros",cloth_by_category_path(:category => "Heros"), :method => :get %>
		</li>	
		<li class="item3">
			<%= link_to "Techs",cloth_by_category_path(:category => "Techs"), :method => :get %>
		</li>
		<li class="item3">
			<%= link_to "Animes",cloth_by_category_path(:category => "Animes"), :method => :get %>
		</li>
		
				
		
	</ul>
		</li>
				
		
	</ul>
					</div>
				<!--initiate accordion-->
		<script type="text/javascript">
			$(function() {
			    var menu_ul = $('.menu > li > ul'),
			           menu_a  = $('.menu > li > a');
			    menu_ul.hide();
			    menu_a.click(function(e) {
			        e.preventDefault();
			        if(!$(this).hasClass('active')) {
			            menu_a.removeClass('active');
			            menu_ul.filter(':visible').slideUp('normal');
			            $(this).addClass('active').next().stop(true,true).slideDown('normal');
			        } else {
			            $(this).removeClass('active');
			            $(this).next().stop(true,true).slideUp('normal');
			        }
			    });
			
			});
		</script>
	     	 	
			</div>
					<div class="fb-like-box" data-href="https://www.facebook.com/mimiberryco" data-width="300px" data-height="271px" data-colorscheme="light" data-show-faces="true" data-header="true" data-stream="false" data-show-border="true"></div>
	<div class="clearfix"> </div>
</div>


<!--shopping cart model  -->
 <div class="modal fade" id="shoppingcart" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
       <div class="modal-dialog">
            <%= render @cart %>
       </div><!-- /.modal-dialog -->
 </div><!-- /.modal -->

app/views/cloths/home_mobile.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
	<!---->
	<!-- start content -->
	<div class="container">
	<ul class="list-group">

	  <li class="list-group-item" id="mobile_header"><h4><label id="mo_doll"></label>Welcome from MIMIberry</h4></li>
	  <li class="list-group-item" id="mobile_header"><h4><label id="mo_van"></label>Free shipping <span class="live">for Yangon Area</span></h4></li>
	  <li class="list-group-item" id="mobile_header">
			<a href="#shoppingcart" data-toggle="modal" style="color:#ffffff;">
			<h4><label id="mo_cart"></label>CART<br/>
			</a>Qty( <%= @cart.total_quantity %> ) | 
			Cash <%= (@cart.total_price) %> Ks</h4>

	  </li>
	</ul>
		
	<div class="women-product">
		<div class=" w_content">
			<div class="women">
				<a href="#"><h4>Sales Item - <span><%= @number_of_cloths %> items</span> </h4></a>
				<ul class="w_nav">
					<li>Sort : </li>
			     	<li><a class="active" href="#">popular</a></li> |
			     	<li><a href="#">new </a></li> |
			     	<li><a href="#">discount</a></li> |
			     	<li><a href="#">price: Low High </a></li> 
			     <div class="clearfix"> </div>	
			     </ul>
			     <div class="clearfix"> </div>	
			</div>
		</div>
		<!-- grids_of_4 -->
		<div class="grid-product">

		<% @cloths.each do |cloth| %>
			<div class=" product-grid" id="mygrid"><br/>
			<div id="mycode">code - <%= cloth.item_code %></div>
			<div class="content_box"><a href="#">
			   	<div class="left-grid-view grid-view-left">
			   	   	  <%= image_tag cloth.avatar.url(:medium), :class =>"img-responsive watch-right", :style =>"width:320px;" %>
				   	   	<div class="mask">
	                        <div class="info">Quick View</div>
			            </div>
				   	  </a>
				   </div>
				    <h4><a href="#"><%= cloth.item_name %> </a></h4>
				     <p>Available size (<%= cloth.available_size %>)<br/>
				        Available color (<%= cloth.available_color %>)</p>
				      
				      <div>
				        <h4 style="float:left;">Price: <%= cloth.price %> Kyats<hr/>
				        <%= button_to 'Add to Cart' , line_items_path(:cloth_id => cloth),:class =>"btn btn-success btn-sm" %>
				        </h4>
				      </div>
			 </div>
             </div>

        <% end %>
			
			<div class="clearfix"> </div>
		</div>
	</div>
				
		<div class=" chain-grid menu-chain">
	   		<a href="#">
	   		<h3 style="text-align:center;">MiMiBerry Online Store is Ecommerce product of</h3>  	
	   		<%= image_tag "hnt.png", :class =>"img-responsive chain" %></a>	
	   		<p style="text-align:center;">Produced an App for Others is worth Living.</p>  		     	</div>
	   		    <a class="view-all all-product" href="#">Facebook<span> </span></a> 
	   		</div><br/>
			<div class="fb-like-box" data-href="https://www.facebook.com/mimiberryco" data-width="100px" data-height="100px" data-colorscheme="light" data-show-faces="true" data-header="true" data-stream="false" data-show-border="true">
			</div>
	<div class="clearfix"> </div>
</div>


<!--shopping cart model  -->
 <div class="modal fade" id="shoppingcart" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
       <div class="modal-dialog">
            <%= render @cart %>
       </div><!-- /.modal-dialog -->
 </div><!-- /.modal -->


 <div class="footer">
		<div class="footer-top">
			<div class="container">
				<div class="latter">
				
					<div class="clearfix"> </div>
				</div>
				<div class="latter-right">
					<p>FOLLOW US</p>
					<ul class="face-in-to">
						<li><a href="#"><span> </span></a></li>
						<li><a href="https://www.facebook.com/mimiberryco"><span class="facebook-in"> </span></a></li>
						<div class="clearfix"> </div>
					</ul>
					<div class="clearfix"> </div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
		<div class="footer-bottom">
			<div class="container">
				<div class="footer-bottom-cate cate-bottom">
					<ul>
						<li class="temp"> <p class="footer-class">Produced by <a href="http://www.hnttechs.com/" target="_blank">H&Ttechs</a> </p></li>
					</ul>
				</div>
			</div>
		</div>
	</div>

app/views/cloths/index.html.erb
<div class="container">
<h3>Cloths DB
<%= link_to 'New Cloth', new_cloth_path, :class=>"btn btn-default" %>
<%= link_to 'New Orders', orders_path, :class=>"btn btn-default" %>
</h3>

<table class="table table-hover">
  <thead>
    <tr>
      <th>ItemCode</th>
      <th>ItemName</th>
      <th>Category</th>
      <th>Size</th>
      <th>Color</th>
      <th>Brand</th>
      <th>ItemPrice</th>
      <th>ItemAvatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cloths.each do |cloth| %>
      <tr>
        <td><%= cloth.item_code %></td>
        <td><%= cloth.item_name %></td>
        <th><%= cloth.category %></th>
        <th><%= cloth.available_size %></th>
        <th><%= cloth.available_color %></th>
        <th><%= cloth.brand %></th>
        <td><%= cloth.price %></td>
        <td><%= image_tag cloth.avatar.url(:thumb) %></td>
        <td><%= link_to 'Show', cloth %></td>
        <td><%= link_to 'Edit', edit_cloth_path(cloth) %></td>
        <td><%= link_to 'Destroy', cloth, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


</div>

app/views/cloths/new.html.erb
<div class="container">

<h1>New cloth</h1>

<%= render 'form' %>

<%= link_to 'Back', cloths_path %>

</div>

app/views/cloths/show.html.erb
<div class="container">

		<h3>Cloth Information</h3>

		<p>
		  <strong>Item code:</strong>
		  <%= @cloth.item_code %>
		</p>

		<p>
		  <strong>Item name:</strong>
		  <%= @cloth.item_name %>
		</p>


        <p>
 			<strong>Item category:</strong>
            <%= @cloth.category %>
        </p>
        <p>
        	<strong>Available Size:</strong>
        	<%= @cloth.available_size %>
        </p>
        <p>
       	<strong>Available Color:</strong>
        <%= @cloth.available_color %></p>

        <p>
       	<strong>Brand:</strong>
        <%= @cloth.brand %></p>


		<p>
		  <strong>Price:</strong>
		  <%= @cloth.price %>
		</p>

		<p>
		   <%= image_tag @cloth.avatar.url(:medium) %>
		</p>

<%= link_to 'Edit', edit_cloth_path(@cloth) %> |
<%= link_to 'Back', cloths_path %>
</div>